blank_issues_enabled: false
contact_links:
  - name: Deltaswap Official Discord
    url: https://discord.gg/deltaswapcrypto
    about: If you're a user, this is the fastest way to get help. Do not give your wallet private key or mnemonic words to anyone.
